server:
  port: 8086
spring:
  cloud:
    config:
     enabled: true
  application:
    name: basketService
  data:
    redis:
      host: redis
      port: 6379
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discoveryserver:9020/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
